schema:
  - ./api/**/*.graphql

exec:
  filename: internal/gql/runtime/generated.go
  package: runtime

model:
  filename: internal/gql/model/generated.go
  package: model

resolver:
  layout: follow-schema
  dir: internal/gql/resolver
  package: resolver
  filename_template: "{name}.go"

models:
  UInt:
    model: github.com/marki-eriker/kim-worker-go/internal/gql/model.UInt
