CREATE TABLE navigation
(
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    path VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    icon VARCHAR(255),
    parent_id BIGINT DEFAULT 0 NOT NULL,
    "order" INTEGER DEFAULT 1 NOT NULL,
    node BOOLEAN DEFAULT FALSE NOT NULL,
    dev BOOLEAN DEFAULT TRUE NOT NULL
);
