// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package request

import (
	"sync"
	"time"
)

// LoaderOrganizationContactByIDConfig captures the config to create a new LoaderOrganizationContactByID
type LoaderOrganizationContactByIDConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []LoaderOrganizationContactByIDKey) ([]*OrganizationContact, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewLoaderOrganizationContactByID creates a new LoaderOrganizationContactByID given a fetch, wait, and maxBatch
func NewLoaderOrganizationContactByID(config LoaderOrganizationContactByIDConfig) *LoaderOrganizationContactByID {
	return &LoaderOrganizationContactByID{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// LoaderOrganizationContactByID batches and caches requests
type LoaderOrganizationContactByID struct {
	// this method provides the data for the loader
	fetch func(keys []LoaderOrganizationContactByIDKey) ([]*OrganizationContact, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[LoaderOrganizationContactByIDKey]*OrganizationContact

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *loaderOrganizationContactByIDBatch

	// mutex to prevent races
	mu sync.Mutex
}

type loaderOrganizationContactByIDBatch struct {
	keys    []LoaderOrganizationContactByIDKey
	data    []*OrganizationContact
	error   []error
	closing bool
	done    chan struct{}
}

// Load a OrganizationContact by key, batching and caching will be applied automatically
func (l *LoaderOrganizationContactByID) Load(key LoaderOrganizationContactByIDKey) (*OrganizationContact, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a OrganizationContact.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *LoaderOrganizationContactByID) LoadThunk(key LoaderOrganizationContactByIDKey) func() (*OrganizationContact, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (*OrganizationContact, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &loaderOrganizationContactByIDBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (*OrganizationContact, error) {
		<-batch.done

		var data *OrganizationContact
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *LoaderOrganizationContactByID) LoadAll(keys []LoaderOrganizationContactByIDKey) ([]*OrganizationContact, []error) {
	results := make([]func() (*OrganizationContact, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	organizationContacts := make([]*OrganizationContact, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		organizationContacts[i], errors[i] = thunk()
	}
	return organizationContacts, errors
}

// LoadAllThunk returns a function that when called will block waiting for a OrganizationContacts.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *LoaderOrganizationContactByID) LoadAllThunk(keys []LoaderOrganizationContactByIDKey) func() ([]*OrganizationContact, []error) {
	results := make([]func() (*OrganizationContact, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]*OrganizationContact, []error) {
		organizationContacts := make([]*OrganizationContact, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			organizationContacts[i], errors[i] = thunk()
		}
		return organizationContacts, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *LoaderOrganizationContactByID) Prime(key LoaderOrganizationContactByIDKey, value *OrganizationContact) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := *value
		l.unsafeSet(key, &cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *LoaderOrganizationContactByID) Clear(key LoaderOrganizationContactByIDKey) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *LoaderOrganizationContactByID) unsafeSet(key LoaderOrganizationContactByIDKey, value *OrganizationContact) {
	if l.cache == nil {
		l.cache = map[LoaderOrganizationContactByIDKey]*OrganizationContact{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *loaderOrganizationContactByIDBatch) keyIndex(l *LoaderOrganizationContactByID, key LoaderOrganizationContactByIDKey) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *loaderOrganizationContactByIDBatch) startTimer(l *LoaderOrganizationContactByID) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *loaderOrganizationContactByIDBatch) end(l *LoaderOrganizationContactByID) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
